version: "3.3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    hostname: uptime-kuma
    environment:
      - PUID=986
      - PGID=983
      - TZ=America/Los_Angeles
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true    
