services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    hostname: uptime-kuma
    environment:
      - PUID=986
      - PGID=983
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /home/closure/docker/uptime-kuma/data:/app/data

networks:
  default:
    name: caddy_net
    external: true    
