version: '3.3'

services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: /PRTS/komga/manga
        target: /manga
    ports:
      - 25600:25600
    user: "984:981"
    environment:
      - PUID=984
      - PGID=981
      - TZ=America/Los_Angeles
      - JAVA_TOOL_OPTIONS=-Xmx8g
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true
