version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/closure/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/closure/caddy/site:/srv
      - /home/closure/caddy/data:/data
      - /home/closure/caddy/config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  default:
    name: caddy_net
    external: true
