version: '3'

services:
  vaultwarden:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    restart: 'unless-stopped'
    env_file:
      - settings.env
    volumes:
      - /home/closure/vaultwarden/data:/data
      - /home/closure/vaultwarden/web-vault:/web-vault
    ports:
      - '3012:3012'
    expose:
      - "80"

networks:
  default:
    name: caddy_net
    external: true
