services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    user: 990:987
    environment:
      - PUID=990
      - PGID=987
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/closure/docker/portainer/data:/data
    expose:
      - "9443"

networks:
  default:
    name: caddy_net
    external: true
