version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    user: 991:988
    environment:
      - PUID=991
      - PGID=988
      - TZ=America/Los_Angeles
    env_file:
      - settings.env
    ports:
      - "3012:3012"
    expose:
      - "80"
    volumes:
      - ./data:/data
      - ./web-vault:/web-vault
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true
