version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 995:991
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - PUID=995
      - PGID=991
    volumes:
      - /home/closure/docker/jellyfin/config:/config
      - /home/closure/docker/jellyfin/cache:/cache
      - /PRTS/jellyfin/anime:/anime
    restart: 'unless-stopped'
    ports:
      - "8096:8096"
      - "1900:1900/udp"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: caddy_net
    external: true
