version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: 994:990
    environment:
      - PUID=994
      - PGID=990
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true
