version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    hostname: caddy
    user: 993:989
    environment:
      - PUID=993
      - PGID=989
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  default:
    external: true
    name: caddy_net
